language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.8"
# command to install dependencies
before_install:
  - sudo apt-get --quiet update
  - sudo pip install --upgrade setuptools
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python setup.py test