language: python

dist: focal

matrix:
  fast_finish: true
  include:
    - python:  '3.10.1'
    - python:  '3.10.2'
    - python:  '3.10'
      dist:  bionic
    - python:  '3.9'
      dist:  bionic
    - python:  '3.8'
    - python:  '3.7'

before_install:
  - sudo apt-get --quiet update

install:
  - pip install .
script:
  - tox